### ISSUE TITLE
[Bug]: Switching Tasks After completing pomo sessions is broken

### ISSUE THREAD

**Issue by RainbowPangolin** [cmwall0605/cse112-sp22-group8#101]
### Summary of the bug:

If you complete a pomo session on a task (whether or not that's the last pomo session or not), then when you switch to a different task, it starts on the break screen rather than the work screen. It also skips the work sessions and loops over the breaks.

For example, Task A has 4 pomo sessions, and Task B has 4. You do 1/4 sessions for Task A. You switch to Task B during the break by going to the task page and selecting it. When you start Task B, the Header displays 1/4 pomos completed, and the timer immediately starts on the alarm that marks the end of a pomo session. Then it goes to Short Break. If you do a short break, then it does another Short Break, rather than going to the work session. Do this again, then it goes to Long Break. 

### Steps to reproduce the bug:

Create multiple tasks -> Do one pomo session of any task (can be 1/1 tasks or 1/4 or any number) -> Switch to other task

**Comment by cmwall0605** [comment]
This issue seems to have been fixed in the most recent PR request, but let me know if it still persists there
