### ISSUE TITLE
[Bug]: Clicking and Unclicking task breaks UI

### ISSUE THREAD

**Issue by RainbowPangolin** [cmwall0605/cse112-sp22-group8#18]
### Gif

https://i.imgur.com/ILvAokp.mp4

### Steps to reproduce the bug:

On To-do List page, click the circle next to a task to mark it as complete, then click it again to unmark it as complete.

Note: Bug behavior is slightly different if you use the Ghostery chrome extension, which a popular Chrome extension that overwrites CSS on every page you visit to simulate dark-mode.

**Comment by cmwall0605** [comment]
Fixed this issue with the task item and task list overhaul
