### ISSUE TITLE
[Refactor]: Accessibility (Style Changes)

### ISSUE THREAD

**Issue by james-c-lars** [cmwall0605/cse112-sp22-group8#3]
- Always use alt text with images, including icons.
    - Thinking: There are a variety of reasons to do this, including for if users have disabled image loading as well as if users are using screen readers.
- Use aria-label with links (like `<a>`) and input elements to describe what they do.
    - Thinking: This is super useful for screen readers, and without them sites quickly become unusable.
- Always use a standard `<label>` with every input element.
    - Thinking: Makes it clear what all the different input elements do.
- Follow ARIA-landmark layout with the following elements having the sematic meanings:
    - `<header>` - banner
    - `<nav>` - navigation
    - `<main>` - main
    - `<aside>` - complementary
    - `<footer>` - contentinfo
    - Thinking: Using these conventions will help structure our page in an easy to understand way for both developers and screen readers.
- Avoid absolute units, especially for text. rem is the preferred standard unit (equivalent to about 16 pixels).
    - Thinking: The user can change the rem by changing their font sizing. This allows for users to request larger text without us needing to manually add that setting.
    - Followup: It would also be handy to have standard text sizes defined using custom properties rather than hard coded, again just to have consistency across our site.

**Comment by RainbowPangolin** [comment]
Most of this was already done. Breaking up into new issues for the remaining bits.
