### ISSUE TITLE
[Feature]: Add notes button to timer page

### ISSUE THREAD

**Issue by james-c-lars** [cmwall0605/cse112-sp22-group8#6]
Add a notes button to the timer page, this was previous suggested in some of the rough wireframing documentation. Can be found at specs/interface/rough/rough_timer.png

**Comment by cmwall0605** [comment]
This might actually be an issue which is encapsulated in the timer landing page set up. Will have to look into that

**Comment by cmwall0605** [comment]
Not gonna be using notes anyone, See ADR for details
