### ISSUE TITLE
[Refactor]: Task List Web Component (OR DEAL WITH WORKAROUND)

### ISSUE THREAD

**Issue by RainbowPangolin** [cmwall0605/cse112-sp22-group8#61]
### Part to be refactored
The Task List does not offer any of the benefits of being a web-component. 

For example, if you create a taskList component, in order to populate it with taskItem components you need to create a form element (or anything that can fire a `submit` event), fill it with about a dozen tags with specific id's, and only then will it function. This also makes it very convoluted to change how we edit or start tasks.

Here is an example if what is needed for the task list's add to function _at all_. You need more to get the rest of the functions to work.

`     <task-list></task-list>
      <form id="taskform">
        <input id="" type="submit" value="Create Boilerplate task"></input>
        <p id="welcome-message"></p>
        <input type="text" id="task-name"  />
        <p id="task-num" value="the value that gets put into the task"></p>
        <p id="task-note"></p>
        <p id="add-task-modal"></p>
      </form>
`

### Refactors to be made

Make the task list work without having to create a bunch of other HTML. 

### Important Note
Theoretically, we can deal with this silliness by just creating the requisite HTML. If we want to, say, 'edit in place' (i.e. when editing a task, you edit the task as it is on the task list, rather than through a modal), then we can just make our modals look like the task items and stick it over the task item through some additional JS. Also, if we want to not have to confirm deletion (right now an extra button is **required** to delete a task), then we are locked out of it. But after some testing it seems like that's the only major thing that can't be solved by my workaround. 

This is hacky, but it's the best workaround I can think of. If we do that, then refactoring will become more silly later down the line, so we need to make a decision as to whether to refactor the task list.

**Comment by cmwall0605** [comment]
After doing a fair amount of work on getting the task-list working, there were some issues which were either fixed because of these changes or deprecated because they no longer applied:
* #8
* #10

**Comment by JIzabal** [comment]
@cmwall0605 For editing in place the `contenteditable` attribute could potentially simplify our issues
